config/routes.rb
Rails.application.routes.draw do
  resources :post_tags

  resources :teacher_classes

  resources :post_types

  resources :tags

  resources :posts

  resources :classrooms

  resources :teachers

  resources :students

  resources :schools

  resources :dashboard

  resources :searches

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
	has_many :students
	has_many :assignments
	has_many :teachers, through: :assignments
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :school
	belongs_to :teacher
	belongs_to :student
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	belongs_to :post
	belongs_to :tag
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :students
	has_many :teachers
	has_many :classes
	has_many :posts



	def short_desc 
		self.description[0..60]
	end

	
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :classroom
	has_many :posts
	delegate :teacher, to: :class
	def self.search(search)
	  if search
	    where('firstname LIKE ?', "%#{search}%")
	  else
	    self
	  end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :school
	has_many :assignments
	has_many :classes, through: :assignments
	has_many :students, through: :class
end

app/models/teacher_class.rb
class TeacherClass < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/models/teacher_classroom.rb
class TeacherClassroom < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:school_id, :firstname, :lastname, :title, :email, :username, :blog_url, :password, :blog_title, :blog_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.text_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br>
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :blog_title %><br>
    <%= f.text_field :blog_title %>
  </div>
  <div class="field">
    <%= f.label :blog_description %><br>
    <%= f.text_area :blog_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>School</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Title</th>
      <th>Email</th>
      <th>Username</th>
      <th>Blog url</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.id %></td>
        <td><%= teacher.school %></td>
        <td><%= teacher.firstname %></td>
        <td><%= teacher.lastname %></td>
        <td><%= teacher.title %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.username %></td>
        <td><%= teacher.blog_url %></td>
        <td><%= teacher.password %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @teacher.school %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @teacher.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @teacher.lastname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @teacher.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @teacher.username %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @teacher.blog_url %>
</p>

<p>
  <strong>Password:</strong>
  <%= @teacher.password %>
</p>

<p>
  <strong>Blog title:</strong>
  <%= @teacher.blog_title %>
</p>

<p>
  <strong>Blog description:</strong>
  <%= @teacher.blog_description %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>