config/routes.rb
Rails.application.routes.draw do
  resources :post_tags

  resources :teacher_classes

  resources :post_types

  resources :tags

  resources :posts

  resources :classrooms

  resources :teachers

  resources :students

  resources :schools

  resources :dashboard

  resources :searches

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
	has_many :students
	has_many :assignments
	has_many :teachers, through: :assignments
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :school
	belongs_to :teacher
	belongs_to :student
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	belongs_to :post
	belongs_to :tag
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :students
	has_many :teachers
	has_many :classes
	has_many :posts



	def short_desc 
		self.description[0..60]
	end

	
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :classroom
	has_many :posts
	delegate :teacher, to: :class
	def self.search(search)
	  if search
	    where('firstname LIKE ?', "%#{search}%")
	  else
	    self
	  end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :school
	has_many :assignments
	has_many :classes, through: :assignments
	has_many :students, through: :class
end

app/models/teacher_class.rb
class TeacherClass < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/models/teacher_classroom.rb
class TeacherClassroom < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApplicationController
  before_action :set_post_tag, only: [:show, :edit, :update, :destroy]

  # GET /post_tags
  # GET /post_tags.json
  def index
    @post_tags = PostTag.all
  end

  # GET /post_tags/1
  # GET /post_tags/1.json
  def show
  end

  # GET /post_tags/new
  def new
    @post_tag = PostTag.new
  end

  # GET /post_tags/1/edit
  def edit
  end

  # POST /post_tags
  # POST /post_tags.json
  def create
    @post_tag = PostTag.new(post_tag_params)

    respond_to do |format|
      if @post_tag.save
        format.html { redirect_to @post_tag, notice: 'Post tag was successfully created.' }
        format.json { render :show, status: :created, location: @post_tag }
      else
        format.html { render :new }
        format.json { render json: @post_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_tags/1
  # PATCH/PUT /post_tags/1.json
  def update
    respond_to do |format|
      if @post_tag.update(post_tag_params)
        format.html { redirect_to @post_tag, notice: 'Post tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_tag }
      else
        format.html { render :edit }
        format.json { render json: @post_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_tags/1
  # DELETE /post_tags/1.json
  def destroy
    @post_tag.destroy
    respond_to do |format|
      format.html { redirect_to post_tags_url, notice: 'Post tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_tag
      @post_tag = PostTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_tag_params
      params.require(:post_tag).permit(:post_id, :tag_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/post_tags/_form.html.erb
<%= form_for(@post_tag) do |f| %>
  <% if @post_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_tag.errors.count, "error") %> prohibited this post_tag from being saved:</h2>

      <ul>
      <% @post_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.text_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_tags/edit.html.erb
<h1>Editing Post Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_tag %> |
<%= link_to 'Back', post_tags_path %>

app/views/post_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Tags</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_tags.each do |post_tag| %>
      <tr>
        <td><%= post_tag.post %></td>
        <td><%= post_tag.tag %></td>
        <td><%= link_to 'Show', post_tag %></td>
        <td><%= link_to 'Edit', edit_post_tag_path(post_tag) %></td>
        <td><%= link_to 'Destroy', post_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post tag', new_post_tag_path %>

app/views/post_tags/new.html.erb
<h1>New Post Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', post_tags_path %>

app/views/post_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_tag.post %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post_tag.tag %>
</p>

<%= link_to 'Edit', edit_post_tag_path(@post_tag) %> |
<%= link_to 'Back', post_tags_path %>