config/routes.rb
Rails.application.routes.draw do
  resources :post_tags

  resources :teacher_classes

  resources :post_types

  resources :tags

  resources :posts

  resources :classrooms

  resources :teachers

  resources :students

  resources :schools

  resources :dashboard

  resources :searches

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
	has_many :students
	has_many :assignments
	has_many :teachers, through: :assignments
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :school
	belongs_to :teacher
	belongs_to :student
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	belongs_to :post
	belongs_to :tag
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :students
	has_many :teachers
	has_many :classes
	has_many :posts



	def short_desc 
		self.description[0..60]
	end

	
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :classroom
	has_many :posts
	delegate :teacher, to: :class
	def self.search(search)
	  if search
	    where('firstname LIKE ?', "%#{search}%")
	  else
	    self
	  end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :school
	has_many :assignments
	has_many :classes, through: :assignments
	has_many :students, through: :class
end

app/models/teacher_class.rb
class TeacherClass < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/models/teacher_classroom.rb
class TeacherClassroom < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :street_address, :street_number, :route, :city, :state, :zip, :country, :email, :username, :blog_url, :password, :description)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :street_number %><br>
    <%= f.number_field :street_number %>
  </div>
  <div class="field">
    <%= f.label :route %><br>
    <%= f.text_field :route %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br>
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schools</h1>

<table class="index">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>City</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Username</th>
      <th>Blog url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.id %></td>
        <td class="med"><%= school.name %></td>
        <td class="med"><%= school.city %></td>
        <td class="med"><%= school.zip %></td>
        <td class="med"><%= school.email %></td>
        <td class="med"><%= school.username %></td>
        <td class="large"><%= school.blog_url %></td>
        <td class="small"><%= link_to 'Show', school %></td>
        <td class="small"><%= link_to 'Edit', edit_school_path(school) %></td>
        <td class="small"><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

    <div id="locationField">
      <input id="autocomplete" placeholder="Enter your address"
             onFocus="geolocate()" type="text"></input>
    </div>


<form class="new_school" id="address" action="/schools" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="0+1W/nRcoNJHBH1qwtVJJbNgMvN6tc0ogZefgQSXWvs+/qq1R7HpiLcLPonWfh/DxFk5NWmotPXoKhJqtZzOEQ==">

<label for="school_name">Name</label><br>
<input name="school[name]" id="school_name"><br>
<label for="street_number">Street number</label><br>
<input name="school[street_number]" id="street_number"><br>
<label for="route">Route</label><br>
<input type="text" name="school[route]" id="route"><br>
<label for="locality">City</label><br>
<input type="text" name="school[city]" id="locality"><br>
<label for="school_state">State</label><br>
<input type="text" name="school[state]" id="administrative_area_level_1"><br>
<label for="school_zip">Zip</label><br>
<input type="number" name="school[zip]" id="postal_code"><br>
<label for="school_country">Country</label><br>
<input type="text" name="school[country]" id="country"><br>
<label for="school_email">Email</label><br>
<input type="text" name="school[email]" id="school_email"><br>
<label for="school_blog_url">Blog Url</label><br>
<input type="text" name="school[blog_url]" id="school_blog_url">
<label for="school_password">Password</label><br>
<input type="password" name="school[password]" id="school_password"><br>
<label for="school_description">Description</label><br>
<input type="description" name="school[description]" id="school_description"><br>
  <div class="actions">
    <input type="submit" name="commit" value="Create School">
  </div>
</form>



<%= link_to 'Back', schools_path %>


 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXoGuFDoxBExbTPyl5Cp4Mke2DhW4teG0&signed_in=true&libraries=places&callback=initAutocomplete"
        async defer></script>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @school.street_number %>
</p>

<p>
  <strong>Route:</strong>
  <%= @school.route %>
</p>

<p>
  <strong>City:</strong>
  <%= @school.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @school.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @school.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @school.country %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @school.username %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @school.blog_url %>
</p>

<p>
  <strong>Password:</strong>
  <%= @school.password %>
</p>

<p>
  <strong>Description:</strong>
  <%= @school.description %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>